# Docker Compose, file version 1
solr:
  build: ./solr-emlo
  restart: always

  volumes:
      - ./data-solr/:/data-solr/

redis:
  image: redis:3.2
  restart: always

pylons:
  build: ./pylons-emlo
  restart: always

  links:
    - solr
    - redis

  volumes:
   - ./data/:/data/
   - ./cache:/emlo/pylons/web/cache

nginx:
  build: ./nginx-emlo
  restart: always

  links:
    - pylons
    - solr

  ports:
    - "80:80"